# project.yml — minimal metadata for reports, dashboards & admin
title: "Project title"
status: "active"                # active | paused | completed
pi: "PI name"
dept: "Department or Division"
analyst: "Lead analyst or TBA"
start_date: "<YYYY-MM-DD>"
expected_end: "<YYYY-MM-DD>"
data_path_from_sharepoint: "Projects/<path-to-project>"
current_data_date: 'YYYY-MM-DD'

biostat_effort_planned:         #
  - person: "<name>"
    role: "faculty"             # faculty | analyst | other
    fte: 0.05
    start: "<YYYY-MM-DD>"
    end: "<YYYY-MM-DD>"
    source: "grant"
    admin_contact: "Unknown"

